### PR TITLE
Prioritize resolution of .then 

### LINKED ISSUE #735: Prioritize resolution by `.then` for thenable functions
Here are a couple simple changes to make function-thenables work as expected and increase compatibility with e.g. Knockout:

### 1. Change [`dust.isThenable`](https://github.com/linkedin/dustjs/blob/master/lib/dust.js#L255) to

```javascript
  dust.isThenable = function(elem) {
    return elem &&
           (typeof elem === 'object' || typeof elem === 'function') &&
           typeof elem.then === 'function';
  };
```

This matches Promises A+ spec, which states ["1.2 “thenable” is an object or function that defines a then method."](https://promisesaplus.com/#point-7)

(As a total aside, you may want to test that `elem !== null` since `typeof null` is `object` and `null.then` will throw an exception.)

### 2. Towards the end of [`Context.prototype._get`](https://github.com/linkedin/dustjs/blob/master/lib/dust.js#L433) change:

- `if (typeof ctx === 'function') {`  to
- `if (typeof ctx === 'function' && !dust.isThenable(ctx)) {`

So if a "thenable function" (a function with a `.then`) is passed in, it prioritizes resolution by via the `.then` over calling the function.

### 3. In [`Chunk.prototype.reference`](https://github.com/linkedin/dustjs/blob/master/lib/dust.js#L255) move:

```javascript
if (dust.isThenable(elem)) {
  return this.await(elem, context, null, auto, filters);
}
```

to the beginning of the function (i.e. before `if (typeof elem === 'function') {`).

### 4.  Add a test, along these lines (pardon the style/naming):

```javascript
describe("references ...", function () {
  it("dereferences via .then on thenable functions", function () {
    var fn = function () { return 'no' }
    fn.then = (res) => "yes"
    dust.renderSource("a{x}b", {x: fn}, (err, out) => assert.equal(out, "ayesb"))
  })
})
``` 

Use case
---

If you are using [Knockout.js](https://github.com/knockout/knockout) (and lots of folks do to) then most view-models passed in will use knockout observables, and look like this:

```javascript
var vm = {
   x: ko.observable()
}
```

These observables are functions; you call them to read the value, write to them by passing the new value as the argument to the same function i.e. `x(123)` sets the value to `123`; `x()` then returns `123`.

When you call dust with this with e.g. `dust.renderSource("{x}", vm, ...)` it modifies the observable, which is undesirable.  (It becomes the `chunk` via ` ctx.apply(ctxThis, arguments);` in `Context.prototype._get`.)

Prioritizing `thenable` over functions makes it trivial for Knockout to expose its value. (For interests sake, until it's built in, KO users need to add something like this: `ko.subscribable.fn.then = function(res) { res(this()) }`).  I also feel like this is the more natural prioritization.

I doubt many folks will have thenable functions, so I suspect this change has a low probability of breakage – and where folks do have thenable functions I suspect the preference is to resolve via the `then` as opposed to a function call.

Thanks for reading; I hope this proves to be a useful request.  Happy to put together a PR, but I just posted here since the changes seem pretty simple.

Cheers.

### PR DESCRIPTION
**Pull request by brianmhunt**
Closes #735

### CODE REVIEW

**Comment by brianmhunt** [comment]
I rebuilt `dist/`, but it contains a few things that I guess had not yet been merged into `master`.  Hope it's alright; they look innocuous, but happy to remove if preferred.

**Comment by brianmhunt** [comment]
Failed on Node 0.10: `Failed: should render streams found while iterating over an array` under the heading `Running unit tests with /home/travis/build/linkedin/dustjs/node_modules/rhino-1_7r5-bin/rhino1_7R5/js.jar`

I've no idea what might be going on there.  :)

File: lib/dust.js [hunk 1]
```diff
@@ -248,17 +248,27 @@
...
   /**
-   * Decide somewhat-naively if something is a Thenable.
+   * Decide somewhat-naively if something is a Thenable.  Matches Promises A+ Spec, section 1.2 “thenable” is an object or function that defines a then method."
    * @param elem {*} object to inspect
    * @return {Boolean} is `elem` a Thenable?
    */
   dust.isThenable = function(elem) {
-    return elem &&
-           typeof elem === 'object' &&
+    return elem &&  /* Beware: `typeof null` is `object` */
```
Comment (sethkinast) [inline lib/dust.js]: We can totally add the null check here

File: lib/dust.js [hunk 2]
```diff
@@ -248,17 +248,27 @@
...
   };
 
   /**
+   * Decide if an element is a function but not Thenable; it is prefereable to resolve a thenable function by its `.then` method.
+   * @param elem {*} target of inspection
+   * @return {Boolean} is `elem` a function without a `.then` property?
+   */
+  dust.isNonThenableFunction = function(elem) {
+    return typeof elem === 'function' &&
+           typeof elem.then !== 'function';
```
Comment (sethkinast) [inline lib/dust.js]: I know it duplicates the logic slightly, but I'd rather delegate to `isThenable` here just to have as few places as possible where we inspect for the magic `then`.

File: dist/dust-core.js [hunk 3]
```diff
@@ -1,6 +1,6 @@
 /*! dustjs-linkedin - v2.7.2
```
Comment (sethkinast) [inline dist/dust-core.js]: Just remove the built files from the diff if you would-- we rebuild when we cut a release rather than on every commit.

**Comment by sethkinast** [comment]
Couple small comments, and a rebase, and 👍  from me

@jimmyhchan @prashn64 @smfoote , one more?

I reran the failing CI test; Rhino isn't the most reliable. Looks fine now.

File: lib/dust.js (hunk 1 above)
Comment (brianmhunt) [inline lib/dust.js]: I had a think about this:  When `elem` is `null` it'll be falsy, so it'll early-out on the `elem && ...`.  Testing for `null` would be redundant (albeit explicit).

There look to be a few tests that ensure this e.g. "scalar null in a # section", so it looks covered.

**Comment by brianmhunt** [comment]
Rebased, typo in the commit message and all. 👀 

Let me know if there's anything else (e.g. the explicit `null` test).

**Comment by sethkinast** [comment]
:+1: looks great
